# Important Notes:
# Every field you add must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.

# Project
version=1.0.0
group=com.denizen.schworlium
java_version=25

# Common
minecraft_version=26.2
mod_name=Schworlium
mod_author=swankydenizen
mod_id=schworlium
license=MIT
credits=Algorithm ported from WorleyCaves by SuperFluke (MIT)
description=Worley-noise caves for Fabric and NeoForge, a port of WorleyCaves.
minecraft_version_range=[26.2, 26.3)
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.2-1

# Fabric, see https://fabricmc.net/develop/ for new versions
fabric_version=0.152.1+26.2
fabric_loader_version=0.19.3

# NeoForge, see https://projects.neoforged.net/neoforged/neoforge for new versions
neoforge_version=26.2.0.1-beta
neoforge_loader_version_range=[4,)

# Lithostitched (provides the wrap_noise_router worldgen modifier we use to disable vanilla noise caves)
lithostitched_fabric_version=1.7.12-fabric-26.2
lithostitched_neoforge_version=1.7.12-neoforge-26.2

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
